### ISSUE TITLE
INSTALL INSSUES

### ISSUE THREAD

**Issue by chhatbarchintan** [Catchxu/STANDS#1]
Thanks for this interesting package. I would like to try it out on visiumHD data. I have installation issues...i used the instructions i got installation error.

Processing dependencies for stands==1.0.0
Searching for sklearn>=1.2.0
Reading https://pypi.org/simple/sklearn/
No local packages or working download links found for sklearn>=1.2.0
error: Could not find suitable distribution for Requirement.parse('sklearn>=1.2.0')

since sklearn is deprecated and replaced by sci-kit learn is this the issue?

**Comment by Catchxu** [comment]
Thanks for your interests for our work! Your solution is correct. Actually, sklearn is an abbreviation of sci-kit learn. We ignored this when dealing with dependencies. Now we have updated setup.py.
