### ISSUE TITLE
How to do data preprocessing?

### ISSUE THREAD

**Issue by caoname** [Catchxu/STANDS#4]
According to tutorial 1, does hbc-G2 set    These three are combined into one .h5ad file, ()? There is also the HCC-V05.H5AD file that has been downloaded, but there is no batch column in his obs, may I ask how this batch comes from?
According to Tutorial 1, hbc-G2 is not going to combine these three {1) gene expression matrix in adata.X; 2) spatial coordinates in adata.obsm['spatial'];  3) histology image in adata.uns['spatial'].} into a.H5ad file, but if you process these three files, how can I ensure that the data structure is the same as in the tutorial (To make the model can read the data sucessfully, please ensure the same anndata structure as example.)? There is also the HBC-V05.h5ad file that has been downloaded, but there is no batch column in his obs, may I ask how this batch comes from?
I would appreciate it if you could answer my questions

**Comment by Catchxu** [comment]
The gene expression matrix, spatial coordinates and images of hBC-G2 need to be merged in the preprocessing step. You just need to read the corresponding data and put it in the corresponding position in the anndata format. I have updated the new preprocessed datasets (see https://catchxu.github.io/STANDS/start/#datasets), which include hBC-G2. I think you can download and check it to make sure that the preprocessing is correct when using your own dataset.

In addition, obs['batch'] in the V05 dataset is not additional information, but an identifier used to mark the dataset. The 'batch' of each spot in the dataset is also consistent (can be uniformly set to 'V05'). The main purpose of introducing this column is that the experiment involves batch alignment between V05 and other datasets, and we need an identifier to distinguish which dataset these spots originally come from. Our provided preprocessed datasets also include V05 for your reference.
