### ISSUE TITLE
Can you provide the processed data?

### ISSUE THREAD

**Issue by luckylucky801** [Catchxu/STANDS#6]
You did a great job! But I encountered some problems when reproducing your work. Basically, all data needs to be preprocessed, but I am not good at data processing. So you can provide the processed data files for us to reproduce your work. If you provide it, we will be very grateful!

**Comment by Catchxu** [comment]
You can see my response to the issue #5 and #4, which includes the data preprocessing steps, and the updated dataset and weights are available for download at https://catchxu.github.io/STANDS/start/#datasets.

**Comment by TaoJiang999** [comment]
![Image](https://github.com/user-attachments/assets/fe69bcf0-de4b-4ea5-9be4-e1e160a20c3c)   Hello, I am reproducing the STANDS code and training the GAN network for anomaly detection. According to your tutorial, the loss becomes NaN. Have you encountered this issue before? How can I solve it?
